name: Daily-Crawl
on:
  schedule:
    - cron: '0 18 * * *' # 한국 시간 새벽 3시 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas streamlit plotly

      - name: Run crawler
        run: python collector.py
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          DEFAULT_KEYWORDS: ${{ secrets.DEFAULT_KEYWORDS }}
          MY_BRAND_1: ${{ secrets.MY_BRAND_1 }}
          MY_BRAND_2: ${{ secrets.MY_BRAND_2 }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 아래 줄이 핵심 변경 사항입니다
          git add -A
          # 변경 사항이 있을 때만 커밋 (에러 방지)
          git commit -m "update ranking: $(date +'%Y-%m-%d')" || exit 0
          git push
